[document-type]
key = "b8188492-dc05-43e6-98bf-04ee758e4c17"
alias = "homePage"
name = "Home Page"
description = "The site's landing page"
icon = "icon-home"
allow-at-root = true
allow-children = ["homePage"]
templates = ["homePage"]
default-template = "homePage"

[[tab]]
name = "Content"

[[tab.property]]
key = "41fc551c-4bc9-4a1e-acab-d3c8a11e35ff"
alias = "title"
name = "Title"
description = "Shown as the page heading"
type = "textstring"
mandatory = true

[[tab.property]]
key = "f4b0420a-125c-49c6-863d-c40ad6f09703"
alias = "bodyText"
name = "Body"
type = "richtext"
