/**
 * `bunbraco generate`: TypeScript for the document types in a schema set, so a
 * view can name a property and have the compiler check it. Umbraco's
 * ModelsBuilder, minus the DLL.
 */
import { BUILTIN_DATA_TYPES, storageTypeFor } from './builtin.ts'
import { allProperties, type SchemaDocumentType, type SchemaSet } from './model.ts'

function pascal(alias: string): string {
  const cleaned = alias.replace(/[^A-Za-z0-9]+(.)?/g, (_, next: string | undefined) =>
    next ? next.toUpperCase() : '',
  )
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
}

/** The element types a block data type allows, by alias, for its content and its settings. */
function blockElements(set: SchemaSet, config: Record<string, unknown>) {
  const blocks = Array.isArray(config.blocks)
    ? (config.blocks as Array<Record<string, unknown>>)
    : []
  const aliasOf = (key: unknown) =>
    typeof key === 'string'
      ? set.documentTypes.find((t) => t.key?.toLowerCase() === key.toLowerCase())?.alias
      : undefined
  const content = blocks.flatMap((b) => aliasOf(b.contentElementTypeKey) ?? [])
  const settings = blocks.flatMap((b) => aliasOf(b.settingsElementTypeKey) ?? [])
  return { content: [...new Set(content)], settings: [...new Set(settings)] }
}

const elementUnion = (aliases: string[]) =>
  aliases.length === 0
    ? 'PublishedElement'
    : aliases.map((a) => `TypedElement<${pascal(a)}>`).join(' | ')

/** What a template receives for a property of this data type (see `@bunbraco/render` values). */
function tsTypeFor(set: SchemaSet, dataTypeAlias: string): string {
  const custom = set.dataTypes.find((d) => d.alias === dataTypeAlias)
  const editor = custom?.editor ?? BUILTIN_DATA_TYPES.find((b) => b.alias === dataTypeAlias)?.editor
  const config =
    custom?.config ?? BUILTIN_DATA_TYPES.find((b) => b.alias === dataTypeAlias)?.config ?? {}
  if (!editor) return 'unknown'
  switch (editor) {
    case 'Umbraco.TrueFalse':
      return 'boolean'
    case 'Umbraco.ContentPicker':
      return 'PublishedContent | null'
    case 'Umbraco.MultiNodeTreePicker':
      return 'PublishedContent[]'
    case 'Umbraco.MultiUrlPicker':
      return 'Link[]'
    case 'Umbraco.ElementPicker': {
      // `allowedContentTypes` is a comma-separated list of element type keys, as
      // Umbraco's AllowedContentTypeKeysParser reads it. Narrowing to those types
      // is what makes `hero.value('body')` typed rather than `unknown`.
      const allowed =
        typeof config.allowedContentTypes === 'string' ? config.allowedContentTypes : ''
      const aliases = allowed
        .split(',')
        .map((key) => key.trim())
        .filter(Boolean)
        .flatMap(
          (key) =>
            set.documentTypes.find((t) => t.key?.toLowerCase() === key.toLowerCase())?.alias ?? [],
        )
      // `Array<>` not `[]`: a union of two element types would otherwise bind as
      // `A | (B[])`.
      return `Array<${elementUnion([...new Set(aliases)])}>`
    }
    case 'Umbraco.Tags':
    case 'Umbraco.CheckBoxList':
    case 'Umbraco.DropDown.Flexible':
    case 'Umbraco.MultipleTextstring':
      return 'string[]'
    case 'Umbraco.UploadField':
      return 'string'
    case 'Umbraco.BlockList': {
      const { content, settings } = blockElements(set, config)
      return `Array<BlockItem & { content: ${elementUnion(content)}; settings: ${settings.length ? `${elementUnion(settings)} | null` : 'PublishedElement | null'} }>`
    }
    case 'Umbraco.BlockGrid': {
      const { content } = blockElements(set, config)
      return `Array<BlockGridItem & { content: ${elementUnion(content)} }>`
    }
  }
  switch (storageTypeFor(editor)) {
    case 'Integer':
    case 'Decimal':
      return 'number'
    case 'Date':
    case 'Nvarchar':
      return 'string'
    default:
      return editor === 'Umbraco.TextArea' || editor === 'Umbraco.RichText' ? 'string' : 'unknown'
  }
}

/** Every property a type carries, including those from its compositions. */
function effectiveProperties(set: SchemaSet, type: SchemaDocumentType, seen = new Set<string>()) {
  if (seen.has(type.alias)) return []
  seen.add(type.alias)
  const out = [...allProperties(type)]
  for (const alias of type.compositions) {
    const composed = set.documentTypes.find((t) => t.alias === alias)
    if (composed) out.push(...effectiveProperties(set, composed, seen))
  }
  return out
}

export function generateTypes(set: SchemaSet): string {
  const out: string[] = [
    '// Generated by `bunbraco generate` from schema/*.toml. Do not edit.',
    '',
    'export interface DocumentTypeProperties {',
  ]
  for (const t of [...set.documentTypes].sort((a, b) => a.alias.localeCompare(b.alias))) {
    out.push(`  ${JSON.stringify(t.alias)}: ${pascal(t.alias)}`)
  }
  out.push('}', '')
  out.push('export type DocumentTypeAlias = keyof DocumentTypeProperties', '')
  for (const t of [...set.documentTypes].sort((a, b) => a.alias.localeCompare(b.alias))) {
    out.push(`/** ${t.name}${t.description ? ` — ${t.description}` : ''} */`)
    out.push(`export interface ${pascal(t.alias)} {`)
    const properties = effectiveProperties(set, t)
    const byAlias = new Map(properties.map((p) => [p.alias, p]))
    for (const p of [...byAlias.values()].sort((a, b) => a.alias.localeCompare(b.alias))) {
      if (p.description) out.push(`  /** ${p.description} */`)
      out.push(`  ${JSON.stringify(p.alias)}${p.mandatory ? '' : '?'}: ${tsTypeFor(set, p.type)}`)
    }
    out.push('}', '')
  }
  // Import only the value types the generated interfaces use.
  const body = out.join('\n')
  const used = [
    'BlockGridItem',
    'BlockItem',
    'Link',
    'PublishedContent',
    'PublishedElement',
    'TypedElement',
  ].filter((name) => new RegExp(`\\b${name}\\b`).test(body.split('\n').slice(2).join('\n')))
  if (used.length > 0) out.splice(2, 0, `import type { ${used.join(', ')} } from 'bunbraco'`, '')
  return `${out.join('\n').trimEnd()}\n`
}
