[document-type]
key = "f80b78ff-2f3d-47ba-a8e6-fb079db4571d"
alias = "journal"
name = "Journal"
description = "A parent for the journal entries"
icon = "icon-newspaper"
allow-children = ["journalEntry"]
collection = "listViewContent"
templates = ["journal"]
default-template = "journal"

[[tab]]
name = "Content"

[[tab.property]]
key = "4da9fd86-9c07-4779-91c0-a2c62599bf18"
alias = "title"
name = "Title"
type = "textstring"
mandatory = true

[[tab.property]]
key = "955781f2-8c17-46a9-8325-f6486e5fb0d4"
alias = "summary"
name = "Summary"
description = "Shown wherever this page is listed"
type = "textarea"

[[tab.property]]
key = "bc987c71-d7f4-431e-9ab4-28df65cc01b3"
alias = "intro"
name = "Introduction"
type = "richtext"
