/**
 * The single seam between the services and SQL. Queries are written once with
 * `?` placeholders and rendered per dialect, so no service ever needs to know
 * which database it is talking to.
 */
export type DialectName = 'sqlite' | 'postgres'

export interface ColumnTypes {
  identity: string
  integer: string
  bigint: string
  boolean: string
  uuid: string
  /** Case-insensitive text. Umbraco compares aliases and logins case-insensitively. */
  textCi: string
  text: string
  varchar: (n: number) => string
  timestamp: string
  numeric: string
  blob: string
}

export interface Dialect {
  readonly name: DialectName
  readonly types: ColumnTypes
  placeholder(index: number): string
  quote(identifier: string): string
  /** Rewrites `?` placeholders into the dialect's own form. */
  render(sql: string): string
  now(): string
  boolValue(value: boolean): unknown
  /** Appended to a SELECT that must block a concurrent state change; empty where the engine is single-writer. */
  readonly forShare: string
  readonly forUpdate: string
  /**
   * SQL that moves a table's identity past rows inserted with explicit ids, or
   * undefined where the engine does that itself.
   */
  syncIdentity(table: string): string | undefined
}

const RESERVED_RENDER = /\?/g

export const sqliteDialect: Dialect = {
  name: 'sqlite',
  types: {
    identity: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    integer: 'INTEGER',
    bigint: 'INTEGER',
    boolean: 'INTEGER',
    uuid: 'TEXT',
    // COLLATE NOCASE is how Umbraco gets case-insensitive aliases on SQLite.
    textCi: 'TEXT COLLATE NOCASE',
    text: 'TEXT',
    varchar: (n) => `VARCHAR(${n}) COLLATE NOCASE`,
    timestamp: 'TEXT',
    // REAL would be lossy for decimal property values.
    numeric: 'TEXT',
    blob: 'BLOB',
  },
  placeholder: () => '?',
  quote: (id) => `"${id.replaceAll('"', '""')}"`,
  render: (sql) => sql,
  now: () => "strftime('%Y-%m-%dT%H:%M:%fZ','now')",
  boolValue: (value) => (value ? 1 : 0),
  forShare: '',
  forUpdate: '',
  syncIdentity: () => undefined,
}

export const postgresDialect: Dialect = {
  name: 'postgres',
  types: {
    identity: 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    integer: 'INTEGER',
    bigint: 'BIGINT',
    boolean: 'BOOLEAN',
    uuid: 'UUID',
    // Postgres collates case-sensitively by default; citext restores Umbraco's semantics.
    textCi: 'CITEXT',
    text: 'TEXT',
    varchar: (n) => `VARCHAR(${n})`,
    timestamp: 'TIMESTAMPTZ',
    numeric: 'NUMERIC',
    blob: 'BYTEA',
  },
  placeholder: (index) => `$${index}`,
  quote: (id) => `"${id.replaceAll('"', '""')}"`,
  render(sql) {
    let i = 0
    return sql.replace(RESERVED_RENDER, () => `$${++i}`)
  },
  now: () => 'now()',
  boolValue: (value) => value,
  forShare: 'FOR SHARE',
  forUpdate: 'FOR UPDATE',
  syncIdentity: (table) =>
    `SELECT setval(pg_get_serial_sequence('${table}', 'id'), (SELECT COALESCE(MAX(id), 1) FROM ${table}))`,
}

export function dialectFor(name: DialectName): Dialect {
  return name === 'sqlite' ? sqliteDialect : postgresDialect
}

/**
 * Timestamps are written as ISO strings in both dialects — SQLite stores TEXT,
 * and Postgres parses ISO into timestamptz — but they read back differently
 * (string vs Date), so every read goes through `fromDb`.
 */
export const DbDate = {
  toDb(value: Date): string {
    return value.toISOString()
  },
  fromDb(value: unknown): Date | undefined {
    if (value === null || value === undefined) return undefined
    if (value instanceof Date) return value
    if (typeof value === 'string') {
      const parsed = new Date(value)
      return Number.isNaN(parsed.getTime()) ? undefined : parsed
    }
    return undefined
  },
}

/** SQLite has no boolean type, so a 0/1 integer comes back for one dialect only. */
export function fromDbBool(value: unknown): boolean {
  return value === true || value === 1 || value === '1' || value === 't'
}
