// Generated by `bunbraco generate` from schema/*.toml. Do not edit.

export interface DocumentTypeProperties {
  contact: Contact
  contentPage: ContentPage
  homePage: HomePage
}

export type DocumentTypeAlias = keyof DocumentTypeProperties

/** Contact Page */
export interface Contact {
  /** test 123 */
  email?: string
}

/** Content Page */
export interface ContentPage {
  bodyText?: string
  /** Shown as the page heading */
  title: string
}

/** Home Page — The site's landing page */
export interface HomePage {
  bodyText?: string
  /** Shown as the page heading */
  title: string
}
