// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "login": {
    "instruction": "سجل الدخول إلى Bunbraco"
  },
  "user": {
    "changePasswordDescription": "يمكنك تغيير كلمة مرورك للوصول إلى واجهة Bunbraco من خلال ملء النموذج أدناه والنقر على زر 'تغيير كلمة المرور'",
    "createUserHelp": "قم بإنشاء مستخدمين جدد لمنحهم الوصول إلى Bunbraco. عند إنشاء مستخدم جديد، سيتم توليد كلمة مرور يمكنك مشاركتها مع المستخدم.",
    "inviteUserHelp": "ادعُ مستخدمين جدد لمنحهم الوصول إلى Bunbraco. سيتم إرسال بريد إلكتروني دعوة إلى المستخدم مع معلومات حول كيفية تسجيل الدخول إلى Bunbraco. تدوم الدعوات لمدة 72 ساعة.",
    "noConsole": "تعطيل الوصول إلى Bunbraco",
    "userCreatedSuccessHelp": "تم إنشاء المستخدم الجديد بنجاح. لتسجيل الدخول إلى Bunbraco استخدم كلمة المرور أدناه.",
    "userInvitedSuccessHelp": "تم إرسال دعوة إلى المستخدم الجديد مع تفاصيل حول كيفية تسجيل الدخول إلى Bunbraco.",
    "userinviteWelcomeMessage": "مرحباً بك في Bunbraco! في دقيقة واحدة فقط ستكون جاهزاً، نحن فقط بحاجة منك لتعيين كلمة مرور وإضافة صورة لملفك الشخصي.",
    "userinviteExpiredMessage": "مرحباً بك في Bunbraco! للأسف انتهت صلاحية دعوتك. يرجى الاتصال بالمسؤول الخاص بك واطلب منهم إعادة إرسالها."
  },
  "general": {
    "umbracoInfo": "معلومات Bunbraco"
  },
  "dashboard": {
    "nothinghappens": "إذا لم يفتح Bunbraco، قد تحتاج إلى السماح بالنوافذ المنبثقة من هذا الموقع"
  },
  "defaultdialogs": {
    "linkYourConfirm": "أنت على وشك ربط حسابك في Bunbraco وحسابك في {0} وسيتم توجيهك إلى {0} للتأكيد.",
    "unLinkYourConfirm": "أنت على وشك إلغاء ربط حسابك في Bunbraco وحسابك في {0} وسيتم تسجيل خروجك."
  }
}
