// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Možete promijeniti lozinku za pristup Bunbraco backofficeu popunjavanjem\n       izađite iz donjeg obrasca i kliknite na dugme 'Promijeni lozinku'\n    ",
    "createUserHelp": "Kreirajte nove korisnike da im date pristup Bunbraco. Kada se novom korisniku kreira lozinka\n       će biti generisano koje možete podijeliti s korisnikom.\n    ",
    "inviteUserHelp": "Pozovite nove korisnike da im daju pristup Bunbraco. E-mail sa pozivom će biti poslan na\n       korisnik s informacijama o tome kako se prijaviti na Bunbraco. Pozivnice traju 72 sata.\n    ",
    "noConsole": "Onemogućite pristup Bunbraco-u",
    "userCreatedSuccessHelp": "Novi korisnik je uspješno kreiran. Za prijavu na Bunbraco koristite\n      lozinka ispod.\n    ",
    "userInvitedSuccessHelp": "Novom korisniku je poslana pozivnica s detaljima o tome kako se prijaviti\n      Bunbraco.\n    ",
    "userinviteWelcomeMessage": "Pozdrav i dobrodošli u Bunbraco! Za samo 1 minut možete krenuti, mi samo trebate postaviti lozinku.",
    "userinviteExpiredMessage": "Dobrodošli u Bunbraco! Nažalost, vaš poziv je istekao. Molimo kontaktirajte svoju\n      administratora i zamolite ih da ga ponovo pošalju.\n    "
  },
  "general": {
    "umbracoInfo": "Bunbraco info"
  },
  "languages": {
    "defaultLanguageHelp": "Bunbraco stranica može imati samo jedan zadani jezik."
  },
  "paste": {
    "errorMessage": "Tekst koji pokušavate zalijepiti sadrži posebne znakove ili formatiranje. Ovo bi moglo biti\n       uzrokovano kopiranjem teksta iz programa Microsoft Word. Bunbraco može automatski ukloniti posebne znakove ili formatiranje, tako da\n       zalijepljeni sadržaj će biti prikladniji za web.\n    "
  },
  "dashboard": {
    "nothinghappens": "Ako se Bunbraco ne otvara, možda ćete morati dozvoliti iskačuće prozore sa ove stranice"
  }
}
