// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "createUserHelp": "Vytvořte nové uživatele a udělte mu přístup do Bunbraco. Po vytvoření nového uživatele bude vygenerováno heslo, které s ním můžete sdílet.",
    "inviteUserHelp": "Pozvěte nové uživatele, a poskytněte jim přístup do Bunbraco. Uživatelům bude zaslán e-mail s pozvánkou a s informacemi o tom, jak se přihlásit do Bunbraco. Pozvánky mají platnost 72 hodin.",
    "userCreatedSuccessHelp": "Nový uživatel byl úspěšně vytvořen. Pro přihlášení do Bunbraco použijte heslo níže.",
    "userInvitedSuccessHelp": "Novému uživateli byla zaslána pozvánka s informacemi, jak se přihlásit do Bunbraco.",
    "userinviteWelcomeMessage": "Dobrý den, vítejte v Bunbraco! Za pouhou 1 minutu budete moci používat Bunbraco. Jenom od vás potřebujeme, abyste si nastavili heslo.",
    "userinviteExpiredMessage": "Vítejte v Bunbraco! Vaše pozvánka bohužel vypršela. Obraťte se na svého správce a požádejte jej, aby jí znovu odeslal."
  },
  "dashboard": {
    "nothinghappens": "Jestli se Bunbraco neotevírá, možná budete muset povolit na tomto webu vyskakovací okna"
  }
}
