// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Gallwch newid eich cyfrinair i gyrchu Swyddfa Gefn Bunbracogan lenwi allan y ffurflen isod a chlicio'r botwm 'Newid Cyfrinair'",
    "createUserHelp": "Creu defnyddwyr newydd i roi hawliau iddynt gyrchu Bunbraco. Pan mae defnyddiwr newydd yn cael ei greu, bydd cyfrinair yn cael ei generadu y gallwch chi rannu gyda'r defnyddiwr.",
    "inviteUserHelp": "Gwahodd defnyddwyr newydd i roi hawliau iddynt gyrchu Bunbraco. Bydd gwahoddiad ebost yn cael ei anfon at y defnyddiwr gyda gwybodaeth ar sut i fewngofnodi i Bunbraco. Mae gwahoddiadau yn para am 72 awr.",
    "noConsole": "Analluogi Mynediad Bunbraco",
    "userCreatedSuccessHelp": "Mae'r defnyddiwr newydd wedi'i greu. Er mwyn mewngofnodi i Bunbraco defnyddiwch y cyfrinair isod.",
    "userInvitedSuccessHelp": "Mae gwahoddiad wedi cael ei anfon at y defnyddiwr newydd gyda manylion ar sut i fewngofnodi i Bunbraco.",
    "userinviteWelcomeMessage": "Helo a chroeso i Bunbraco! Mewn 1 munud yn unig, byddech chi'n barod i fynd, rydym dim ond angen gosod cyfrinair.",
    "userinviteExpiredMessage": "Croeso i Bunbraco! Yn anffodus, mae eich gwahoddiad wedi terfynu. Cysylltwch â'ch gweinyddwr a gofynnwch iddynt ail-anfon."
  },
  "general": {
    "umbracoInfo": "Gwybodaeth Bunbraco"
  },
  "dashboard": {
    "nothinghappens": "Os nad yw Bunbraco yn agor, efallai byddwch angen galluogi popups o'r safle yma"
  }
}
