// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Puedes cambiar tu contraseña para acceder al 'back office' de Bunbraco rellenando el siguiente formulario y haciendo clic en el botón 'Cambiar contraseña'",
    "createUserHelp": "Crear nuevos usuarios para darles acceso a Bunbraco. Cuando un nuevo usuario es creado, una nueva contraseña será generada y la podrás compartir con el usuario.",
    "inviteUserHelp": "Invita nuevos usuarios para darles acceso a Bunbraco. Un email de invitación será enviado al usuario con información sobre cómo acceder a Bunbraco.",
    "noConsole": "Deshabilitar acceso a Bunbraco",
    "userCreatedSuccessHelp": "Se ha creado el nuevo usuario con éxito. Para acceder a Bunbraco usa la contraseña siguiente.",
    "userInvitedSuccessHelp": "Se ha enviado una invitación al nuevo usuario con detalles sobre cómo acceder a Bunbraco.",
    "userinviteWelcomeMessage": "¡Hola y bienvenido a Bunbraco!. En un minuto todo estará listo para empezar, sólo necesitamos que configures tu contraseña."
  },
  "dashboard": {
    "nothinghappens": "Si Bunbraco no se ha abierto tendrás que permitir ventanas emergentes para este sitio Web"
  }
}
