// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Vous pouvez changer votre mot de passe d'accès au backoffice Bunbraco en remplissant le formulaire ci-dessous puis en cliquant sur le bouton \"Changer le mot de passe\"",
    "createUserHelp": "Créer de nouveaux utilisateurs pour leur donner accès à Bunbraco. Lors de la création d'un nouvel utilisateur, un mot de passe est généré que vous pouvez partager avec ce dernier.",
    "inviteUserHelp": "Inviter de nouveaux utilisateurs pour leur donner accès à Bunbraco. Un email d'invitation sera envoyé à chaque utilisateur avec des informations concernant la connexion à Bunbraco. Les invitations sont valables pendant 72 heures.",
    "noConsole": "Désactiver l'accès Bunbraco",
    "userCreatedSuccessHelp": "Le nouvel utilisateur a été créé avec succès. Utilisez le mot de passe ci-dessous pour la connexion à Bunbraco.",
    "userInvitedSuccessHelp": "Une invitation a été envoyée au nouvel utilisateur avec les détails concernant la connexion à Bunbraco.",
    "userinviteWelcomeMessage": "Bien le bonjour et bienvenue dans Bunbraco! Vous serez prêt.e dans moins d'1 minute, vous devez encore simplement configurer votre mot de passe.",
    "userinviteExpiredMessage": "Bienvenue dans Bunbraco! Malheureusement, votre invitation a expiré. Veuillez contacter votre administrateur et demandez-lui de vous l'envoyer à nouveau."
  },
  "dashboard": {
    "nothinghappens": "Si Bunbraco ne s'ouvre pas, peut-être devez-vous autoriser l'ouverture des popups pour ce site."
  }
}
