// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Možete promijeniti svoju lozinku za pristup Bunbraco Back Officeu tako da ispunite donji obrazac i kliknete gumb \"Promjeni lozinku\"",
    "createUserHelp": "Kreirajte nove korisnike kako biste im omogućili pristup Bunbraco-u. Kada se kreira novi korisnik, stvorit će se lozinka koju možete podijeliti s korisnikom.\n    ",
    "inviteUserHelp": "Pozovite nove korisnike da im omogućite pristup Bunbraco-u. Korisniku bit će poslan email s pozivnicom i informacijama o tome kako se prijaviti u Bunbraco. Pozivnice traju 72 sata.\n    ",
    "noConsole": "Onemogućite pristup Bunbraco-u",
    "userCreatedSuccessHelp": "Novi korisnik je uspješno kreiran. Za prijavu na Bunbraco koristite\n      lozinka ispod.\n    ",
    "userInvitedSuccessHelp": "Novom korisniku je poslana pozivnica s detaljima o tome kako se prijaviti u Bunbraco.",
    "userinviteWelcomeMessage": "Pozdrav i dobrodošli u Bunbraco! Jedna minuta bit će vam potrebna da postavite svoju lozinku.",
    "userinviteExpiredMessage": "Dobrodošli u Bunbraco! Nažalost pozivnica je istekla. Molimo kontaktirajte svog administratora i od njega tražite da ju ponovno pošalje."
  },
  "general": {
    "umbracoInfo": "Bunbraco info"
  },
  "languages": {
    "defaultLanguageHelp": "Bunbraco stranica može imati samo jedan zadani jezik."
  },
  "paste": {
    "errorMessage": "Tekst koji pokušavate zalijepiti sadrži posebne znakove ili formatiranje. Ovo bi moglo biti\n       uzrokovano kopiranjem teksta iz programa Microsoft Word. Bunbraco može automatski ukloniti posebne znakove ili formatiranje, tako da\n       zalijepljeni sadržaj će biti prikladniji za web.\n    "
  },
  "dashboard": {
    "nothinghappens": "Ako se Bunbraco ne otvara, možda ćete morati dozvoliti skočne prozore sa ove stranice"
  }
}
