// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "È possibile modificare la password di accesso al backoffice Bunbraco compilando il form sottostante e clicca sul pulsante 'Modifica password'",
    "createUserHelp": "Crea nuovi utenti per dar loro accesso a Bunbraco. Quando un nuovo utente viene creato,\n      una nuova password da condividere con l'utente viene generata.\n    ",
    "inviteUserHelp": "Invita nuovi utenti per dar loro l'accesso a Bunbraco. Un'email contenente le informazioni su come effettuare l'accesso in Bunbraco verrà inviata all'utente. Un invito dura per 72 ore.",
    "noConsole": "Disabilita l'accesso ad Bunbraco",
    "userCreatedSuccessHelp": "Il nuovo utente è stato creato correttamente. Per effettuare il login in Bunbraco utilizza la password sottostante.",
    "userInvitedSuccessHelp": "Un invito è stato invitato al nuovo utente con le istruzioni su come effettuare il login in Bunbraco.",
    "userinviteWelcomeMessage": "Ciao e benvenuto su Bunbraco! In solo 1 minuto sarai pronto a partire, dovrai\n      solamente impostare una password.\n    ",
    "userinviteExpiredMessage": "Benvenuto su Bunbraco! Purtroppo il tuo invito è scaduto. Per favore contatta l'amministratore e chiedigli di rispedirlo."
  },
  "visuallyHiddenTexts": {
    "searchOverlayTitle": "Cerca nel backoffice di Bunbraco"
  },
  "languages": {
    "defaultLanguageHelp": "Un sito web Bunbraco può avere solo una lingua di default."
  },
  "paste": {
    "errorMessage": "Il testo che stai cercando di incollare contiene caratteri speciali o una formattazione. Questo potrebbe essere causato da Microsoft Word. Bunbraco può rimuovere carattere speciali o formattazioni automaticamente, per rendere il contenuto da incollare più adatto per il web."
  },
  "dashboard": {
    "nothinghappens": "se Bunbraco non si sta aprendo, potresti aver bisogno di rimuovere il blocco popup"
  },
  "logViewer": {
    "searchUmbracoSource": "Ricerca nel codice sorgente di Bunbraco",
    "searchWithinUmbracoSourceCodeOnGithub": "Ricerca nel codice sorgente di Bunbraco su GitHub",
    "searchUmbracoIssues": "Ricerca tra i problemi di Bunbraco",
    "searchUmbracoIssuesOnGithub": "Ricerca tra i problemi di Bunbraco su GitHub"
  }
}
