// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Bunbracoの管理画面にアクセスするためのパスワードを変更するには、以下のフォームに新しいパスワード入力して「パスワードの変更」ボタンをクリックしてください。",
    "noConsole": "Bunbracoへのアクセスを無効にする"
  },
  "paste": {
    "errorMessage": "貼り付けようとしたテキストは、特殊文字や書式設定が含まれます。これは、Microsoft Wordからテキストをコピーしたりすると発生する事です。Bunbracoでは貼り付けられたコンテンツをウェブに適用させる為、書式や特殊文字を自動的に削除します。"
  },
  "dashboard": {
    "nothinghappens": "Bunbracoが起動しない時は、このサイトのポップアップを許可してください。"
  }
}
