// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Bunbracoの管理画面にアクセスするためのパスワードを変更するには、以下のフォームに新しいパスワード入力して「パスワードの変更」ボタンをクリックしてください。",
    "noConsole": "Bunbracoへのアクセスを無効にする"
  },
  "dashboard": {
    "nothinghappens": "Bunbracoが起動しない時は、このサイトのポップアップを許可してください。"
  }
}
