// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "You can change your password for accessing the Bunbraco backoffice by filling out the form below and click the 'Change Password' button",
    "noConsole": "Bunbraco 접속 비활성화"
  },
  "dashboard": {
    "nothinghappens": "Bunbraco 가 열리지 않으면, 이 사이트의 팝업을 허용하여야 합니다"
  }
}
