// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "login": {
    "userInviteWelcomeMessage": "Hei og velkommen til Bunbraco! Om bare 1 minutt er du klar til å starte, vi trenger bare at du setter et passord.",
    "userInviteExpiredMessage": "Velkommen til Bunbraco! Dessverre har invitasjonen din utløpt. Kontakt administratoren din og be dem sende den på nytt."
  },
  "user": {
    "changePasswordDescription": "Du kan endre passordet til Bunbraco ved å fylle ut skjemaet under og klikke \"Bytt passord\" knappen.",
    "noConsole": "Deaktiver tilgang til Bunbraco"
  },
  "general": {
    "umbracoInfo": "Bunbraco-info"
  },
  "dashboard": {
    "nothinghappens": "Hvis Bunbraco ikke starter, kan det skyldes at pop-up vinduer ikke er tillatt"
  }
}
