// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "você pode alterar sua senha para acessar a área administrativa do Bunbraco preenchendo o formulário abaixo e clicando no botão 'Alterar Senha'",
    "noConsole": "Desabilitar Acesso Bunbraco"
  },
  "dashboard": {
    "nothinghappens": "Se Bunbraco não estiver abrindo talvez você precise hablitar pop-ups para este site"
  }
}
