// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "login": {
    "instruction": "Iniciar sessão no Bunbraco"
  },
  "user": {
    "changePasswordDescription": "Pode alterar a sua palavra-passe para aceder ao backoffice do Bunbraco preenchendo o formulário abaixo e clicando no botão 'Alterar Palavra-passe'",
    "createUserHelp": "Crie novos utilizadores para lhes dar acesso ao Bunbraco. Quando um novo utilizador é criado, será gerada uma palavra-passe que pode partilhar com o utilizador.",
    "inviteUserHelp": "Convide novos utilizadores para lhes dar acesso ao Bunbraco. Será enviado um email de convite ao utilizador com informação sobre como iniciar sessão no Bunbraco. Os convites duram 72 horas.",
    "noConsole": "Desativar Acesso Bunbraco",
    "userCreatedSuccessHelp": "O novo utilizador foi criado com sucesso. Para iniciar sessão no Bunbraco, use a palavra-passe abaixo.",
    "userInvitedSuccessHelp": "Foi enviado um convite ao novo utilizador com detalhes sobre como iniciar sessão no Bunbraco.",
    "userinviteWelcomeMessage": "Olá e bem-vindo(a) ao Bunbraco! Em apenas 1 minuto estará pronto, só precisamos que configure uma palavra-passe e adicione uma imagem para o seu avatar.",
    "userinviteExpiredMessage": "Bem-vindo(a) ao Bunbraco! Infelizmente, o seu convite expirou. Por favor, contacte o seu administrador e peça-lhe para o reenviar."
  },
  "general": {
    "umbracoInfo": "Informação Bunbraco"
  },
  "dashboard": {
    "nothinghappens": "Se o Bunbraco não estiver a abrir, poderá ter de permitir popups deste site"
  },
  "defaultdialogs": {
    "linkYourConfirm": "Está prestes a ligar as suas contas Bunbraco e {0} e será redirecionado para {0} para confirmar.",
    "unLinkYourConfirm": "Está prestes a desligar as suas contas Bunbraco e {0} e será desconectado."
  }
}
