// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Вы можете сменить свой пароль для доступа к административной панели Bunbraco, заполнив нижеследующие поля и нажав на кнопку 'Изменить пароль'",
    "createUserHelp": "Создавайте новых пользователей, которым нужен доступ к административной панели Bunbraco. При создании пользователя для него генерируется новый первичный пароль, который нужно сообщить пользователю.",
    "inviteUserHelp": "Пригласите новых пользователей, которым нужен доступ к административной панели Bunbraco. Приглашенному будет направлено электронное письмо с инструкциями по доступу к Bunbraco.",
    "noConsole": "Отключить доступ к административной панели Bunbraco",
    "userInvitedSuccessHelp": "Новому пользователю было отправлено приглашение, в котором содержатся инструкции для входа в панель Bunbraco.",
    "userinviteWelcomeMessage": "Здравствуйте и добро пожаловать в Bunbraco! Все будет готово в течении пары минут, нам лишь нужно задать Ваш пароль для входа."
  }
}
