// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "login": {
    "userInviteWelcomeMessage": "Hej och välkommen till Bunbraco! Inom bara 1 minut är du redo att börja, vi behöver bara att du ställer in ett lösenord.",
    "userInviteExpiredMessage": "Välkommen till Bunbraco! Tyvärr har din inbjudan gått ut. Vänligen kontakta din administratör och be dem skicka den igen."
  },
  "user": {
    "changePasswordDescription": "Du kan byta ditt lösenord för Bunbraco backoffice genom att fylla i nedanstående formulär och klicka på knappen \"Ändra lösenord\".",
    "createUserHelp": "Skapa nya användare för att ge dom åtkomst till Bunbraco. När en ny användare skapas kommer ett lösenord genereras som du kan dela med användaren.",
    "inviteUserHelp": "Bjud in nya användare för att ge dom åtkomst till Bunbraco. Ett e-postmeddelande kommer skikcas till användaren med information om hur man loggar in i Bunbraco. Inbjudningar är giltiga i 72 timmar.",
    "noConsole": "Inaktivera tillgång till Bunbraco"
  },
  "visuallyHiddenTexts": {
    "searchOverlayTitle": "Sök i Bunbraco backoffice"
  },
  "paste": {
    "errorMessage": "Texten du försöker klistra in innehåller specialtecken och/eller formateringstaggar. Detta kan bero på att texten kommer från t.ex. Microsoft Word. Bunbraco kan ta bort specialtecken och formateringstaggar automatiskt så att innehållet lämpar sig bättre för webbpublicering."
  },
  "dashboard": {
    "nothinghappens": "Om Bunbraco inte öppnas kan det bero på att du måste tillåta poppuppfönster att öppnas från denna webbplats"
  }
}
