// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Aşağıdaki formu doldurarak ve 'Şifreyi Değiştir' düğmesini tıklayarak Bunbraco Arka Ofisine erişim şifrenizi değiştirebilirsiniz",
    "createUserHelp": "Bunbraco'ya erişim sağlamak için yeni kullanıcılar oluşturun. Yeni bir kullanıcı oluşturulduğunda, kullanıcıyla paylaşabileceğiniz bir şifre oluşturulacaktır.",
    "inviteUserHelp": "Yeni kullanıcıları Bunbraco'ya erişim vermeleri için davet edin. Kullanıcıya, Bunbraco'da nasıl oturum açılacağına dair bilgiler içeren bir davet e-postası gönderilecektir. Davetler 72 saat sürer.",
    "noConsole": "Bunbraco Erişimini Devre Dışı Bırak",
    "userCreatedSuccessHelp": "Yeni kullanıcı başarıyla oluşturuldu. Bunbraco'da oturum açmak için aşağıdaki şifreyi kullanın.",
    "userInvitedSuccessHelp": "Yeni kullanıcıya, Bunbraco'da nasıl oturum açılacağına ilişkin ayrıntıları içeren bir davetiye gönderildi.",
    "userinviteWelcomeMessage": "Merhabalar, Bunbraco'ya hoş geldiniz! Sadece 1 dakika içinde hazır olacaksınız, sadece bir şifre belirlemeniz.",
    "userinviteExpiredMessage": "Bunbraco'ya hoş geldiniz! Maalesef davetinizin süresi doldu. Lütfen yöneticinizle iletişime geçin ve yeniden göndermesini isteyin."
  },
  "dashboard": {
    "nothinghappens": "Bunbraco açılmıyorsa, bu siteden pop-up'lara izin vermeniz gerekebilir"
  }
}
