// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "user": {
    "changePasswordDescription": "Ви можете змінити свій пароль для доступу до адміністративної панелі Bunbraco, заповнивши нижченаведені поля та натиснувши кнопку 'Змінити пароль'",
    "createUserHelp": "Створюйте нових користувачів, яким потрібний доступ до адміністративної панелі Bunbraco. При створенні користувача генерується новий первинний пароль, який потрібно повідомити користувачеві.",
    "inviteUserHelp": "Запросіть нових користувачів, яким потрібний доступ до адміністративної панелі Bunbraco. Запрошеному буде надіслано електронного листа з інструкціями щодо доступу до Bunbraco.",
    "noConsole": "Вимкнути доступ до адміністративної панелі Bunbraco",
    "userInvitedSuccessHelp": "Новому користувачеві було надіслано запрошення, яке містить інструкції для входу в панель Bunbraco.",
    "userinviteWelcomeMessage": "Привіт і ласкаво просимо до Bunbraco! Все буде готове протягом декількох хвилин, нам потрібно задати пароль для входу."
  }
}
