// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "login": {
    "instruction": "Đăng nhập vào Bunbraco"
  },
  "user": {
    "changePasswordDescription": "Bạn có thể thay đổi mật khẩu của mình để truy cập vào Bunbraco backoffice bằng cách điền vào mẫu dưới đây và nhấp vào nút 'Đổi mật khẩu'",
    "createUserHelp": "Tạo người dùng mới để cấp quyền truy cập cho họ vào Bunbraco. Khi một người dùng mới được tạo, một mật khẩu sẽ được tạo ra mà bạn có thể chia sẻ với người dùng đó.",
    "inviteUserHelp": "Mời người dùng mới để cấp quyền truy cập cho họ vào Bunbraco. Một email mời sẽ được gửi đến người dùng với thông tin về cách đăng nhập vào Bunbraco. Thời gian hiệu lực của lời mời là 72 giờ.",
    "noConsole": "Vô hiệu hóa quyền truy cập Bunbraco",
    "userCreatedSuccessHelp": "Người dùng mới đã được tạo thành công. Để đăng nhập vào Bunbraco, hãy sử dụng mật khẩu bên dưới.",
    "userInvitedSuccessHelp": "Một lời mời đã được gửi đến người dùng mới với thông tin chi tiết về cách đăng nhập vào Bunbraco.",
    "userinviteWelcomeMessage": "Xin chào và chào mừng bạn đến với Bunbraco! Chỉ trong 1 phút, bạn sẽ sẵn sàng sử dụng. Chúng tôi chỉ cần bạn tạo mật khẩu và thêm hình đại diện cho tài khoản.",
    "userinviteExpiredMessage": "Chào mừng bạn đến với Bunbraco! Rất tiếc, lời mời của bạn đã hết hạn. Vui lòng liên hệ với quản trị viên của bạn và yêu cầu họ gửi lại lời mời."
  },
  "general": {
    "umbracoInfo": "Thông tin Bunbraco"
  },
  "buttons": {
    "viewSystemDetails": "Xem thông tin hệ thống Bunbraco CMS và số phiên bản"
  },
  "visuallyHiddenTexts": {
    "searchOverlayTitle": "Tìm kiếm trong Bunbraco backoffice"
  },
  "languages": {
    "defaultLanguageHelp": "Một trang Bunbraco chỉ có thể có một ngôn ngữ mặc định được thiết lập."
  },
  "paste": {
    "errorMessage": "Văn bản bạn đang cố dán chứa các ký tự hoặc định dạng đặc biệt. Điều này có thể do việc sao chép văn bản từ Microsoft Word. Bunbraco có thể tự động loại bỏ các ký tự hoặc định dạng đặc biệt, vì vậy nội dung được dán sẽ phù hợp hơn với web."
  },
  "dashboard": {
    "nothinghappens": "Nếu Bunbraco không mở, bạn có thể cần cho phép cửa sổ bật lên từ trang này"
  },
  "defaultdialogs": {
    "linkYourConfirm": "Bạn sắp liên kết tài khoản Bunbraco và {0} của mình và bạn sẽ được chuyển hướng đến {0} để xác nhận.",
    "unLinkYourConfirm": "Bạn sắp hủy liên kết tài khoản Bunbraco và {0} của mình và bạn sẽ bị đăng xuất."
  }
}
