// Generated by `bun run localizations:build`. Do not edit.
// The product name in this language's own wording, for the keys
// plugin/branding/localization-en.js curates.
export default {
  "dashboard": {
    "nothinghappens": "如果Bunbraco沒有打開，您可能需要允許彈出式視窗。"
  }
}
