/**
 * Reports how much of the vendored contract is implemented, grouped by area, and
 * writes docs/api-coverage.md. Fails when a previously-implemented operation has
 * regressed to a 501 stub.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createManagementApiRouter, EMPTY_SETTINGS_OPERATIONS } from '@bunbraco/api-management'
import { createBackOfficePaths } from '@bunbraco/backoffice-host'
import { bunbracoPlan, connect, migrate } from '@bunbraco/data'
import { PublishedCache } from '@bunbraco/render'
import { createDeps, createPublishedContentSource, loadConfig } from '@bunbraco/server'

const ROOT = join(import.meta.dir, '..')
const OUT = join(ROOT, 'docs/api-coverage.md')

// Built from the real composition root, with a throwaway database, so the report
// counts every handler that actually ships rather than only the stateless ones.
const paths = createBackOfficePaths()
const db = await connect({ dialect: 'sqlite', file: ':memory:' })
await migrate(db, bunbracoPlan)
const router = createManagementApiRouter({
  deps: createDeps({
    config: loadConfig(),
    paths,
    appPluginsDir: join(ROOT, 'apps/site/App_Plugins'),
    db,
    cache: new PublishedCache(createPublishedContentSource(db)),
  }),
})

interface AreaCoverage {
  area: string
  total: number
  implemented: number
}

const byArea = new Map<string, AreaCoverage>()
for (const op of router.operations) {
  const area = op.area ?? '(none)'
  const entry = byArea.get(area) ?? { area, total: 0, implemented: 0 }
  entry.total += 1
  if (router.has(op.operationId)) entry.implemented += 1
  byArea.set(area, entry)
}

const areas = [...byArea.values()].sort(
  (a, b) => b.implemented - a.implemented || b.total - a.total || a.area.localeCompare(b.area),
)
const total = router.operations.length
const implemented = router.implementedCount
const stubbed = EMPTY_SETTINGS_OPERATIONS.filter((op) => router.has(op)).length
const pct = ((implemented / total) * 100).toFixed(1)

const lines = [
  '# API coverage',
  '',
  '<!-- Generated by `bun run coverage:api`. Do not edit. -->',
  '',
  `**${implemented} / ${total} operations implemented (${pct}%)** — ${implemented - stubbed} real, ${stubbed} answering an honest empty page for areas not yet built (\`handlers/settings-stubs.ts\`).`,
  '',
  '| Area | Implemented | Total |',
  '| --- | --- | --- |',
  ...areas.map((a) => `| ${a.area} | ${a.implemented} | ${a.total} |`),
  '',
]
writeFileSync(OUT, lines.join('\n'))

console.log(`${implemented}/${total} operations implemented (${pct}%)`)
console.log(`wrote ${OUT.replace(`${ROOT}/`, '')}`)

await db.close()

const baseline = Number(Bun.env.BUNBRACO_COVERAGE_BASELINE ?? 0)
if (implemented < baseline) {
  console.error(`coverage regressed: ${implemented} < baseline ${baseline}`)
  process.exit(1)
}
