/**
 * Generates a backoffice localisation override per UI language.
 *
 * `plugin/branding/localization-en.js` is hand-written, and the keys it covers
 * are the editorial decision about which strings name the product rather than a
 * real .NET thing: `appsettings.json`, IIS permissions and the installer are
 * deliberately left alone. This takes that same key set and, for every other
 * language the vendored client ships a dictionary for, rewrites the product
 * name in that language's own wording.
 *
 * Run as the last step of `vendor:backoffice`, or on its own with
 * `bun run localizations:build`.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import english from '../packages/backoffice-host/plugin/branding/localization-en.js'
import { PLUGIN_PATH_PLACEHOLDER } from '../packages/backoffice-host/src/paths.ts'

const ROOT = join(import.meta.dir, '..')
const VENDOR_MANIFEST = join(
  ROOT,
  'packages/backoffice-dist/dist/packages/core/localization/manifests.js',
)
const LANG_DIR = join(ROOT, 'packages/backoffice-dist/dist/assets/lang')
const PLUGIN_DIR = join(ROOT, 'packages/backoffice-host/plugin')
const OUT_DIR = join(PLUGIN_DIR, 'localizations')

/** The cultures the hand-written English override already covers. */
const HAND_WRITTEN = new Set(['en', 'en-us'])

/**
 * Strings that name a configuration key or a path rather than the product. None
 * of the curated keys carry one in English, but a translator may have left an
 * example in, and renaming `Umbraco:CMS:Global:UseHttps` would be a lie.
 */
const NAMES_SOMETHING_REAL = /umbraco\.com|umbraco:|umbracocms|appsettings|web\.config|\/umbraco\//i

/** Every culture the client registers a dictionary file for, in manifest order. */
function vendoredCultures(): { culture: string; file: string }[] {
  const source = readFileSync(VENDOR_MANIFEST, 'utf8')
  const pattern =
    /culture:\s*'([^']+)'\s*\},\s*js:\s*\(\)\s*=>\s*import\('[^']*lang\/([^']+)\.js'\)/g
  const found: { culture: string; file: string }[] = []
  for (const [, matched, file] of source.matchAll(pattern)) {
    if (!matched || !file) continue
    const culture = matched.toLowerCase()
    if (!HAND_WRITTEN.has(culture)) found.push({ culture, file })
  }
  return found
}

/**
 * French elides `de` before a vowel, so its dictionaries carry `d'Umbraco`.
 * Bunbraco opens on a consonant, where the elision is wrong — so the article
 * comes back rather than being left as `d'Bunbraco`.
 */
const ELIDED = /\bd['\u2019](?=Umbraco)/g

export function rebrand(value: string): string | undefined {
  if (!/umbraco/i.test(value) || NAMES_SOMETHING_REAL.test(value)) return undefined
  return value
    .replace(ELIDED, 'de ')
    .replaceAll('Umbraco', 'Bunbraco')
    .replaceAll('umbraco', 'bunbraco')
}

/** The `section.key` pairs the English override curates, flattened. */
export function curatedKeys(overrides: Record<string, Record<string, string>>): [string, string][] {
  return Object.entries(overrides).flatMap(([section, entries]) =>
    Object.keys(entries).map((key): [string, string] => [section, key]),
  )
}

/** The branded subset of one language's dictionary, or undefined if it names nothing. */
export function brandDictionary(
  dictionary: Record<string, Record<string, string> | undefined>,
  keys: readonly [string, string][],
): Record<string, Record<string, string>> | undefined {
  const branded: Record<string, Record<string, string>> = {}
  for (const [section, key] of keys) {
    const value = dictionary[section]?.[key]
    if (typeof value !== 'string') continue
    const corrected = rebrand(value)
    if (corrected === undefined) continue
    branded[section] ??= {}
    branded[section][key] = corrected
  }
  return Object.keys(branded).length > 0 ? branded : undefined
}

const aliasOf = (culture: string) =>
  `Bunbraco.Localization.${culture.toUpperCase().replaceAll('-', '_')}`

export async function buildLocalizations(): Promise<number> {
  const keys = curatedKeys(english as Record<string, Record<string, string>>)
  const { version } = JSON.parse(
    readFileSync(join(PLUGIN_DIR, 'umbraco-package.json'), 'utf8'),
  ) as { version: string }

  rmSync(OUT_DIR, { recursive: true, force: true })
  mkdirSync(OUT_DIR, { recursive: true })

  const extensions: unknown[] = []
  for (const { culture, file } of vendoredCultures()) {
    const module = (await import(join(LANG_DIR, `${file}.js`))) as {
      default: Record<string, Record<string, string> | undefined>
    }
    const branded = brandDictionary(module.default, keys)
    if (!branded) continue

    writeFileSync(
      join(OUT_DIR, `${culture}.js`),
      `// Generated by \`bun run localizations:build\`. Do not edit.\n` +
        `// The product name in this language's own wording, for the keys\n` +
        `// plugin/branding/localization-en.js curates.\n` +
        `export default ${JSON.stringify(branded, null, 2)}\n`,
    )
    extensions.push({
      type: 'localization',
      alias: aliasOf(culture),
      name: `Bunbraco Localization Overrides (${culture})`,
      weight: 0,
      meta: { culture },
      js: `${PLUGIN_PATH_PLACEHOLDER}/localizations/${culture}.js`,
    })
  }

  writeFileSync(
    join(OUT_DIR, 'umbraco-package.json'),
    `${JSON.stringify(
      {
        $schema: '../../../backoffice-dist/dist/umbraco-package-schema.json',
        name: 'Bunbraco Localizations',
        id: 'Bunbraco.Localizations',
        version,
        allowPublicAccess: false,
        extensions,
      },
      null,
      2,
    )}\n`,
  )
  return extensions.length
}

if (import.meta.main) {
  const count = await buildLocalizations()
  console.log(`localizations: branded ${count} cultures`)
}
